# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jEYrhbXtwWSB2iX4Flj6e3HR0ODsHjmA
"""


import streamlit as st
import pickle
import pandas as pd


# Load Models
severity_model = pickle.load(open("project/accuracysevirity.pkl", "rb"))
alert_model = pickle.load(open("project/aelertgenerated.pkl", "rb"))

st.title("🚨 Accident Prediction System")

# User Input
temperature = st.number_input("Temperature")
humidity = st.number_input("Humidity")
vehicle_count = st.number_input("Vehicle Count")
avg_speed = st.number_input("Average Speed")
visibility = st.number_input("Visibility")
accident_occurred = st.selectbox("Accident Occurred", [0,1])

if st.button("Predict"):

    input_data = pd.DataFrame([[temperature, humidity, vehicle_count,
                                avg_speed, visibility, accident_occurred]],
                                columns=['temperature','humidity','Vehicle_Count',
                                'Avg_Speed(km/h)','Visibility(m)','Accident_Occurred'])

    severity = severity_model.predict(input_data)
    alert = alert_model.predict(input_data)

    st.success(f"Accident Severity: {severity[0]}")
    st.warning(f"Alert Generated: {alert[0]}")

